server:
  port: 8089
  servlet:
    context-path: /api

endpoints:
  embed-file: /vk/files

rest:
  client:
    service:
      bankbookEIP-url: "https://epc-api.rt.ru/apiman-gateway/epc-wc/srv-dispatcher/1.8.5?apikey=0eb58769-34f6-4960-bb72-e2d31eafc6a6"

spring:
  application:
    name: embed-file
#  jackson:
    # Отключаем запись дат в виде таймстампов (чисел), чтобы Instant сериализовался в формате ISO-8601 (строка)
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: false
    # Поддержка корректного часового пояса при парсинге дат
#    deserialization:
#      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false

app:
  external-api:
    base-url: https://external.service

#  ALL < TRACE < DEBUG < INFO < WARN < ERROR < FATAL < OFF

logging:
  config: classpath:logback.xml
  level:
    root: INFO
    ru.ruslan: debug
    org.springframework.web: INFO
